baseURL = 'https://www.flyingfortressgames.com'
#baseURL = 'https://guillaumemaiano.github.io/FFG_Site'
locale = 'en-us'
title = 'Flying Fortress Games'
enableRobotsTXT = true
theme = 'IndustrialOptimism'

defaultContentLanguage = 'en'

[languages.en]
title = 'Flying Fortress Games'
weight = 1

[languages.fr]
title = 'Flying Fortress Games'
weight = 2

[cascade]
  [cascade.params]
    author = "Flying Fortress Games"

#[outputs]
#home = ['HTML', 'RSS']
