baseURL = 'https://flyingfortressgames.com/'
locale = 'en-us'
title = 'Flying Fortress Games'
enableRobotsTXT = true
theme = 'IndustrialOptimism'

[params]
youtube_channel_url = "https://www.youtube.com/channel/UCUmA6UM0ePoChw0iGA9eDRg"

defaultContentLanguage = 'en'

[languages.en]
title = 'Flying Fortress Games'
weight = 1

[languages.fr]
title = 'Flying Fortress Games'
weight = 2

[cascade]
  [cascade.params]
    author = "Flying Fortress Games"

#[outputs]
home = ['HTML', 'RSS']

[[menus.main]]
name = 'DEVLOG'
pageRef = '/journal'
weight = 10

[[menus.main]]
name = 'PROJECTS'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'ABOUT'
pageRef = '/about'
weight = 30

[[menus.main]]
name = 'CONTACT'
pageRef = '/contact'
weight = 40
