baseURL = 'https://www.flyingfortressgames.com/'
locale = 'en-us'
title = 'Flying Fortress Games'
enableRobotsTXT = true

defaultContentLanguage = 'en'

[languages.en]
title = 'Flying Fortress Games'
weight = 1

[languages.fr]
title = 'Flying Fortress Games'
weight = 2

theme = "IndustrialOptimism"
[cascade]
  [cascade.params]
    author = "Flying Fortress Games"